# Generated by Django 3.0.3 on 2020-02-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='document',
        ),
    ]
