# Generated by Django 3.0.3 on 2020-02-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_document_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='csv_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
